# Generated by Django 5.2.8 on 2025-11-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='comissao_valor',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Obs (Banco/Detalhes)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_pagamento',
            field=models.CharField(choices=[('vista', 'À vista / PIX'), ('financiado', 'Financiamento'), ('cartao', 'Cartão de crédito')], default='vista', max_length=20),
        ),
    ]
